### ISSUE TITLE
Update to latest MicroPython (1.19.1)

### ISSUE THREAD

**Issue by Develeon64** [Drincann/Pico-Go#4]
## What are the steps to reproduce this issue?
1. Create new project
2. Generate project configuration via the plugins command

## What happens?
MicroPython 1.15.0 is added to the project for IDE assistance.

## What were you expecting to happen?
Latest MicroPython is added to the project

## Any other comments?
Latest version is needed for support of the Raspberry Pi Pico W and it's new functions like networking.

**Comment by andrew-stclair** [comment]
I have just created a Pull Request on Josverl/micropython-stubs for the Pico W running MicroPython v1.19.1

Found here: https://github.com/Josverl/micropython-stubs/pull/611
